### ISSUE TITLE
Parsing urllib3 http request stream

### ISSUE THREAD

**Issue by themmes** [cartoonist/pystream-protobuf#13]
Dear Ali,

Thanks for your work on this library, it seems to be the tool I need! I tried to parse a file from a stream, however have no luck so far.

```
url = 'https://download.geofabrik.de/antarctica-latest.osm.pbf' #29MB

http = urllib3.PoolManager()
response = http.request('GET', url, preload_content=False)

nodes = []
with stream.open(response.data, mode='rb', gzip=False) as istream:
    for data in istream:
        node = osmformat_pb2.Node()
        node.ParseFromString(a)
        nodes.append(node)
```

where `osmformat_pb2.Node()` is (in original .proto format):

```
message Node {
   required sint64 id = 1;
   // Parallel arrays.
   repeated uint32 keys = 2 [packed = true]; // String IDs.
   repeated uint32 vals = 3 [packed = true]; // String IDs.

   optional Info info = 4; // May be omitted in omitmeta

   required sint64 lat = 8;
   required sint64 lon = 9;
}
```

The error I am getting is:

```
ValueError: embedded null byte
```

I tried wrapping the `response.data` in a BytesIO object, which returns the error `expected bytes not BytesIO object`
I probably am doing something stupid here, but I cannot figure what to do to solve this. Could you maybe show how to use `pystream-protobuf` with an `urllib3` request?

**Comment by cartoonist** [comment]
Thanks Tom,

I have no working experience with OSM PBF files. I looked over the file format. As far as I understand, the PBF files are ordered concatenation of several protobuf messages whose sizes are given in a BlobHeader message. According to their [wiki](https://wiki.openstreetmap.org/wiki/PBF_Format#File_format):

> The format is a repeating sequence of:
>   - int4: length of the BlobHeader message in network byte order
>   - serialized BlobHeader message
>   - serialized Blob message (size is given in the header)

So, there are some issues here:

First, this library is developed to parse the streams that are encoded by itself or the original ["vgteam/stream"](https://github.com/vgteam/stream) library. The file format is a repeating sequence of:
- varint64: number of messages (let say `n`)
- varint64: size of the message
- message data
- varint64: size of the message
- message data
... _it repeats `n` times_

If I am not mistaken, this library cannot parse the OSM PBF files/streams out of the box. But it may parse the Blob messages if they are encoded in the same format.

Second, the `stream.open` expects file path as the first argument. But `response.data` is given which contains the actual OSM PBF data. That explains the error message:

    ValueError: embedded null byte

To use with an `urllib3` response, as you said,  wrap `response.data` in a BytesIO object. But you have to pass the BytesIO object through `fileobj` keyword argument to the `open` method (or `Stream` class):

```python
with stream.open(fileobj=io.BytesIO(response.data), mode='rb', gzip=False) as istream:
    #            ^^^^^^^
    # then work with `istream` as before...
```

I hope it helps,

**Comment by themmes** [comment]
Thank you so much for your extensive answer! The understanding that there is a hierarchy of blobs first and then messages really helps. I can now successfully read the file and will experiment with parsing the blobs first and then the messages.
