### ISSUE TITLE
python 2.7  ImportError: No module named builtins

### ISSUE THREAD

**Issue by GergelyMolnar** [cartoonist/pystream-protobuf#14]
Hi,

**ImportError: No module named builtins** Python 2 doesn't have `builtins` module.

I bumped into this issue when I tried to run this package on a machine that has only `Python 2.7.5` installed
OS:
`Linux version 3.10.0-957.27.2.el7.x86_64 (@@@centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36)`

The code is very simple and directly adapted from your examples (I've used `@` just to mask some info)

```
import stream
from @@@@ import @@@@@@@@@@@_basic_pb2

fname = "./sample_data/@@@@@@@@@@@.@@@data"
# message_list = [m for m in stream.parse(fname, @@@@@@@@@@@_basic_pb2.StreamMessage(), gzip=False)]

message_list = []
with stream.open(fname, 'rb', gzip=False) as istream:
    for data in istream:
        msg = @@@@@@@@@@@_basic_pb2.StreamMessage()
        msg.ParseFromString(data)
        message_list.append(msg)

for m in message_list:
    print(m.timestamp)
```

And the actual error
```
/usr/bin/python2.7 /home/@@@@/PycharmProjects/melon/melon/pystream_protobuf_tryout.py
Traceback (most recent call last):
  File "/home/@@@@/PycharmProjects/melon/melon/pystream_protobuf_tryout.py", line 10, in <module>
    with stream.open(fname, 'rb', gzip=False) as istream:
  File "/usr/lib/python2.7/site-packages/stream/stream.py", line 59, in open
    return Stream(filename, mode, **kwargs)
  File "/usr/lib/python2.7/site-packages/stream/stream.py", line 120, in __init__
    import builtins
ImportError: No module named builtins

Process finished with exit code 1
```

I hope this helps.
Thanks

**Comment by cartoonist** [comment]
Hi,

Have you tried to install `future` package for Python 2.7 by `pip2 install future`? I think it would resolve the issue.

**Comment by cartoonist** [comment]
I assumed that the commit resolved the issue, so I close it. Feel free to re-open it in case the issue still exists.
