### ISSUE TITLE
async generator compatibility layer breaks async_parse on python 3.8.2

### ISSUE THREAD

**Issue by ryannathans** [cartoonist/pystream-protobuf#18]
When I run my app I get the following exception trying to use async_parse.

```
/media/ryannathans/G Spot/Git/game/game/client/network.py:50: RuntimeWarning: coroutine 'async_parse' was never awaited
Coroutine created at (most recent call last)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/media/ryannathans/G Spot/Git/game/game/client/network.py", line 20, in run
    asyncio.run(self._main(), debug=True)
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1851, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/media/ryannathans/G Spot/Git/game/game/client/network.py", line 50, in _recv_task
    async for message in stream.async_parse(self._reader, ServerPb.ServerMessage):
  async for message in stream.async_parse(self._reader, ServerPb.ServerMessage):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

The workaround is to replace the `yield_` lines with the real `yield` as such (and remove the decorator):
```
async def async_parse(ifp, pb_cls, **kwargs):
    """Parse an async stream.

    Args:
        ifp (file-like object): input async stream.
        pb_cls (protobuf.message.Message.__class__): The class object of
            the protobuf message type encoded in the stream.
    """
    with open(fileobj=ifp, mode='rb', **kwargs) as istream:
        async for data in istream:
            if isinstance(data, istream.delimiter_class()):
                yield data
            else:
                pb_obj = pb_cls()
                pb_obj.ParseFromString(data)
                yield pb_obj
```

**Comment by cartoonist** [comment]
Hi @ryannathans,

I believe we use `async_generator` package (from where the decorator and `yield_` statement come) for supporting Python 3.5 (see commit 57288cd1c5a8eecea799e0b7256ee8c41e5028b0). Could you please provide a minimum working example to reproduce the exception since no test currently catches this issue?

**Comment by ryannathans** [comment]
This is so bizarre, I copied my failing code (1 file with no dependence on the rest of the project) to a clone of your git repo and it runs fine...

But it doesn't in my virtual environment for my project. So I thought it was a venv incompatibility, so I made a new venv and it works fine... I copied my project across to the new venv and it's running fine... 

Out of curiosity I did a diff on the two virtual environments and there are a few differences in python3 binary!

Turns out the cause is a bug in the python3 binary that has since been fixed, phew!

Sorry to bother you, will close this

**Comment by cartoonist** [comment]
That's indeed very strange. No problem at all. It reminded me that Python 3.5 is going to retire soon and I am going to stop using `async_generator` and revert commit 57288cd. I have to wait a couple of months though since I have no idea which packages are using it under Python 3.5 and I don't want to break them.
