### ISSUE TITLE
support streaming bytes, not only protocol messages

### ISSUE THREAD

**Issue by jrouquie** [cartoonist/pystream-protobuf#20]
Feature request:

The low-level method open supports reading a file and iterating over bytes, ie just before calling ParseFromString: https://github.com/cartoonist/pystream-protobuf/wiki/Reading-from-a-stream#low-level-method-open
How about adding the same support on the writing side, ie add an option not to call SerializeToString?

This would allows to use the library with anything that can be serialized to bytes, not only protocol messages.

**Comment by cartoonist** [comment]
Hi @jrouquie,

Cool feature. This commit (61c25a2f471d630b9d95a5a1fd2b43665c437e2a) adds a `serialize` keyword argument which gets a function. Any function can be given to Stream class by this argument which serializes input objects to byte strings. This can also be `lambda obj: obj` for your purpose.

**Comment by cartoonist** [comment]
Merged with `master` and included in v1.6.3 release. Feel free to reopen if there is any problem.
