### ISSUE TITLE
Document how to build / test package from within repository

### ISSUE THREAD

**Issue by stefanseefeld** [cartoonist/pystream-protobuf#8]
I'm trying to build, test, and run `pystream-protobuf` from the repository, but I run into different issues, such as 
```
$ python setup.py build
  File "setup.py", line 21
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
```
or, when using python3:
```
$ python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    with codecs.open(os.path.join(_HERE, 'README.rst'), encoding='utf-8') as rm_f:
  File "/usr/lib64/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/stefan/projects/pystream-protobuf/README.rst'
```

It would be useful to have clear instructions (including requirements, for example if it is known not to work with Python 2.x).

(I may have a few patches to contribute, so this is merely an attempt to get in touch and get started. :-) )

**Comment by cartoonist** [comment]
Great! Thanks for reporting these issues. I did some changes to make the package compatible for Python 2.7. Please check the `develop` branch, I think it would fix the first issue.

Regarding the second issue, I used to use Markdown for README files in the "git repository", but, as far as I know, it should be in reStructuredText format for distributing python packages. So, I usually convert README from Markdown to reStructuredText format using `pandoc` and include it in the distribution tarball hosted on PyPI.

If you have installed `pandoc`, you can convert it directly or use provided Makefile:

    make README.rst

I do not know how to make this conversion transparent; maybe convert it to 'rST' internally in setup script or only have one version in 'rST' and remove the Markdown version. I would really appreciate if you may have friendlier alternative.

Apart from file formatting, the README file desperately needs to be revised. As you mentioned, it is not complete and have redundant information. I will create a separate issue for this.

**Comment by stefanseefeld** [comment]
Excellent, thanks ! How to you execute the tests under `tests/` ? That would be useful info for the `README`, too.
(Speaking of which, I do believe github supports ReST. At least a reasonable subset. That would be far easier than having to convert to from MarkDown on each build, wouldn't it ?

**Comment by cartoonist** [comment]
In order to install dependencies, and run tests:

    make init  # install dependencies
    make test  # run tests

These also should be added to the README file.

I have just learned that PyPI now supports Markdown (finally!). No need to ReST anymore. :)

**Comment by stefanseefeld** [comment]
Even better. :-)
What is the expectation for protobuf version < 3 support ? I'm trying to work with version 2.6 (part of Ubuntu 16), and I get test errors. I don't yet know how serious they are. (For one, I had to adjust the proto file as `syntax="proto3"` obviously isn't recognized, and I had to insert lots of `required`.
But what about the code in the `stream` module itself ?

**Comment by cartoonist** [comment]
The protobuf package in most distributions is really outdated, however, most of them offers protobuf>=3.0.0 which has been released for almost two years. In my opinion, it is better to uninstall the version installed by Ubuntu and install the latest stable release.

The minimum version required by `stream` module is 3.4.0, however it should work with most versions>3.0.0.

**Comment by stefanseefeld** [comment]
Perhaps that's what I'll have to do. But Ubuntu 16 doesn't include any protobuf 3 packages. So I'll have to figure out whether it's easier to apply backward-compatibility patches to this (`pystream-protobuf` repo) or to build my own protobuf 3 packages for our in-house use.
